batch-size: 30
maxlen-in: 800
maxlen-out: 150
sortagrad: 0
opt: adadelta
epochs: 2
patience: 3
sampling-probability: 0.0
etype: blstmp
elayers: 4
eunits: 320
eprojs: 320
subsample: '1_2_2_1_1'
dlayers: 1
dunits: 300
atype: location
adim: 320
aconv-chans: 10
aconv-filts: 100
mtlalpha: 1.0
use-frontend: true
