
#CUDAROOT=/usr/local/cuda
#NCCL_ROOT=/path/to/nccl

#export CPATH=$NCCL_ROOT/include:$CPATH
#export LD_LIBRARY_PATH=$NCCL_ROOT/lib/:$CUDAROOT/lib64:$LD_LIBRARY_PATH
#export LIBRARY_PATH=$NCCL_ROOT/lib/:$LIBRARY_PATH
#export CFLAGS="-I$CUDAROOT/include $CFLAGS"
#export CPATH=$CUDAROOT/include:$CPATH
#export CUDA_HOME=$CUDAROOT
#export CUDA_PATH=$CUDAROOT

CUDAROOT=/usr/local/cuda

export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDAROOT/include $CFLAGS"
export CPATH=$CUDAROOT/include:$CPATH
export CUDA_HOME=$CUDAROOT
export CUDA_PATH=$CUDAROOT

